### PR TITLE
WIP: Split out classes into separate files

### PR DESCRIPTION
**Pull request by adamduren**
Apologies if this PR seems a bit extreme. I only split out the classes into multiple files so that it is more manageable going forward. Maps are an important part of the ecosystem and I would like to help the effort to make this the go to Google Mapping plugin

### CODE REVIEW

**Comment by adamduren** [comment]
I split out the classes into multiple files so that it is easier to digest this project for contributors. I am interested in helping maintain both the `ionic-native` plugin as well as the `cordova` one in any way that I can.

**Comment by wf9a5m75** [comment]
Did you build and test it on browser, android, and iOS?
I tried couple of times, but I faced JS loading problem perphaps browser.

Actually, I prefer one single file instead of multiple file.
I need to provide `ionic-native v4(master branch)` and `ionic-native v5(v5 branch)`.
Both branches are need to be synchronize, but code are different (mostly the same).

One single file makes me easy to copy& paste, then modify it.
Managing multiple file increase my job.

**Comment by wf9a5m75** [comment]
Did you build and test it on browser, android, and iOS?
I tried couple of times, but I faced JS loading problem parphaps browser.

Actually, I prefer one single file instead of multiple file.
I need to provide `ionic-native v4(master branch)` and `ionic-native v5(v5 branch)`.
Both branches are need to be synchronize, but code are different (mostly the same).

One single file makes me easy to copy& paste, then modify it.
Managing multiple file increase my job, actually.

**Comment by adamduren** [comment]
What if we were to have file parity between the `master` and `v5` branches? That is something I can take on as well and verify both version build and load correctly. In the end `v5` will be being merged into `master` correct? From an engineering perspective it would be better to have the files split out than one big 30,000 line file.

**Comment by wf9a5m75** [comment]
I appreciate if you create test case instead of spreading files.

And I aware `tslint` of `v5` branch is not perfect.
Some points you figured out in PR#100 did not discovered by `tslint` (`npm run test`).
I appreciate if you fixed the settings. (I think configuration mistake or something).

**Comment by adamduren** [comment]
> > In the end v5 will be being merged into master correct?
> 
> I guess no. Why? Ask to the ionic native team at https://github.com/ionic-team/ionic-native

Because `v5` will come out of `beta` and then there will be no reason for it not to be master. For maintenance reasons there should be a `v4` fork. As far as writing tests that is something that I can do however it normally makes sense to have multiple `spec` files that correspond to the class under test which would also go along with splitting out the single `index.ts` into multiple files. We can put this MR on hold for now until we have test coverage to feel good about moving forward wit it.

**Comment by wf9a5m75** [comment]
The reason of branch name `v5` is current `@ionic-native` series use `v4.xxx`.
That's why the ionic native team decided `v5` branches, I guess.
Since I'm not member of ionic team, I don't know the details.
(And I'm not interested in about that)

`@ionic-native/google-maps` has been spin out project from `@ionic-native` repository for many reasons.
However this repository is still under the `ionic-team`.
That's why I keep file structure is the same with [ionic-native](https://github.com/ionic-team/ionic-native) repo as much as possible.

`@ionic-native/google-maps` is just a wrapper plugin for me. I add/modify new properties/methods/classes after I implemented new features in [cordova-plugin-googlemaps](https://github.com/mapsplugin/cordova-plugin-googlemaps).
That's why one big file does not become a big problem for me so far.

**Pull request closed without merging**
